# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FindAFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  	pod 'SDWebImage'
	pod 'GoogleMaps', '~> 2.5'
	pod 'GooglePlaces', '~> 2.5'

  target 'FindAFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FindAFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
